### ISSUE TITLE
Character movement synchronization not fluid

### ISSUE THREAD

**Issue by Kyoril** [Kyoril/mmo#26]
Other characters movement is applied simply as teleport events. This makes characters teleport around when they move. Their movement should be extrapolated locally between movement update packages to make movement of other players appear more fluid.

**Comment by qbq-ber-robin-klimonow** [comment]
I fixed this issue recently by simulating remote movement of units on the local client.
Fixed commit is a8cfac5194e38aa7db5c5400937ab3fbaaa0327e
